### ISSUE TITLE
Docker installs can mount the theme as volumes without needing backups.

### ISSUE THREAD

**Issue by hvalev** [joelacus/deluge-web-dark-theme#5]
Hey, great theme. A suggestion for Docker installs is to download and extract the theme within a folder somewhere, and mount the individual paths to the icons, images and themes directories as volumes. Example below:
```
deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    volumes:
      # dark theme
      - ~/docker_config/deluge/ui/icons:/usr/lib/python3/dist-packages/deluge/ui/web/icons
      - ~/docker_config/deluge/ui/images:/usr/lib/python3/dist-packages/deluge/ui/web/images
      - ~/docker_config/deluge/ui/themes:/usr/lib/python3/dist-packages/deluge/ui/web/themes
```
